fixing ruff errors
AFMC-MAJCOM/task-queue pull request #28
Opened 2024-07-17 22:14 UTC by JS-USAF

2024-07-19 19:04 UTC, JR-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        wf:
Add description for what these parameters are.

2024-07-19 19:05 UTC, JR-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        Return metadata label
Follow the same format as the other doc strings. New line above the "Returns:". Remove "Return" from "Return metadata label"

2024-07-19 19:06 UTC, JR-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        """Gets workflow item's ID
Adjust as per the two comments above about doc strings.

2024-07-19 19:06 UTC, JR-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        """Gets the status of the workflow
Adjust as per the comments about doc strings

2024-07-19 19:07 UTC, JR-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        """Gets the creation timestamp for the workflow from metadata
Adjust as per the comments about doc strings

2024-07-19 19:14 UTC, JR-USAF commented on data_pipeline/argo_workflows_queue_worker.py
I don't know if removing this affected the tests, but the argo tests no longer pass.
![image](https://github.com/user-attachments/assets/64b5ab12-0ff1-450f-a9fd-e89e9a26eed4)

2024-07-19 19:16 UTC, JR-USAF commented on data_pipeline/in_memory_queue.py
> +        partial(lookup_status, memory_queue),
why was it required to change from "in_memory_queue" to "memory_queue"

2024-07-19 19:18 UTC, JR-USAF commented on data_pipeline/work_queue_web_api.py
> +    @staticmethod
Why can't we remove the unused argument?

2024-07-19 19:57 UTC, JR-USAF requested changes

2024-07-19 19:57 UTC, JR-USAF commented on data_pipeline/__init__.py
> +__version__ = "0.0.9"
In .github/workflows/runners.yml.

Add in the requirement for pylint and ruff to pass before publish-docker-image and create-git-tag can be run. All you need to do is add them to the list already there.
```
  publish-docker-image:
    needs: [pytest-linux] # ADD THESE WHEN THEY PASS!!!, pylint, ruff]

create-git-tag:
    needs: [pytest-linux] # ADD THESE WHEN THEY PASS!!!, pylint, ruff]
```

2024-07-19 20:36 UTC, pn-usaf commented on data_pipeline/argo_workflows_queue_worker.py
> +        wf:
there should be a newline after the first line

2024-07-19 20:39 UTC, pn-usaf commented on data_pipeline/argo_workflows_queue_worker.py
> +        """Gets workflow item's ID
there should be a newline between the first line and the second of the doc string

2024-07-19 20:40 UTC, pn-usaf commented on data_pipeline/argo_workflows_queue_worker.py
> +        """Gets the status of the workflow
there should be a newline between the first line and the second line of the docstring

2024-07-19 20:45 UTC, BE-USAF commented on data_pipeline/argo_workflows_queue_worker.py
I think the problem is the url_concat function. Move that out of the class and remove self as the argument,

OR

rework everywhere it is called to pass in the self reference.

2024-07-19 20:45 UTC, BE-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +    def urlconcat(self, *components):
Move out of the class and remove self as the argument,

OR

rework everywhere it is called to pass in the self reference.

2024-07-19 20:46 UTC, pn-usaf commented on data_pipeline/in_memory_queue.py
> +class InMemoryQueue():
I'm not sure if this is intended, in Python when there's an underscore the class is protected and double underscore the class is private. Maybe double check with Nick.

2024-07-19 20:51 UTC, pn-usaf commented on data_pipeline/in_memory_queue.py
will the function return false if an exception is raised? or will the function just terminate on the exception.

2024-07-19 20:58 UTC, pn-usaf commented on data_pipeline/in_memory_queue.py
>          InMemoryQueue object
Check with Nick or someone about the underscore

2024-07-19 21:14 UTC, pn-usaf commented on data_pipeline/work_queue_web_api.py
> +
should there be some code/logic in replace of pass?

2024-07-19 21:26 UTC, pn-usaf commented on data_pipeline/events/in_memory_event_store.py
> +            event.id = len(self.events[event.name])
I not sure what the intention of the _id, I'm assuming that it's protected within the namespace. Maybe double check with someone.

2024-07-19 21:56 UTC, pn-usaf commented on data_pipeline/queue_worker_interface.py
> +
I'm not sure, but should we raised an exception in the abstract method. So that it must be override.
@abstractmethod
def send_job()
____raise NotImplementedError("Please Implement this method")

2024-07-19 21:58 UTC, pn-usaf commented on data_pipeline/queue_worker_interface.py
> -        pass
I'm not sure, but should we raised an exception in the abstract method. So that it must be override.
@AbstractMethod
def poll_all_status()
____raise NotImplementedError("Please Implement this method")

2024-07-19 22:01 UTC, pn-usaf commented on data_pipeline/sql_queue.py
> +        if item is None:
Nice Catch!!! I seen this many times.

2024-07-19 22:08 UTC, pn-usaf commented on tests/common_queue.py
>          pass
Should the exception be handled? Will the exception halt execution?

2024-07-19 22:10 UTC, pn-usaf commented on tests/common_queue.py
>          pass
Should the exception be handled? Will the exception halt execution?

2024-07-22 15:19 UTC, JS-USAF commented on data_pipeline/events/in_memory_event_store.py
> +            event.id = len(self.events[event.name])
id in the event class it comes from is not protected so I don't think it needs to be protected

2024-07-22 15:29 UTC, JS-USAF commented on data_pipeline/in_memory_queue.py
The function should only return true if the try succeeds and won't need to print exceptions so that is why the return True is within the try. If it fails, the goal is to continue running and just return false. By printing out the exception it resolves bare except ruff errors.

2024-07-22 15:32 UTC, JS-USAF commented on data_pipeline/in_memory_queue.py
> +        partial(lookup_status, memory_queue),
There was an invalid name error from pylint for InMemoryQueue function. By changing that to in_memory_queue the parameters for these functions were named the same as the function in_memory_queue , so then I renamed them to fix a redefinition error from pylint

2024-07-22 15:37 UTC, pn-usaf commented on data_pipeline/events/in_memory_event_store.py
> +            event.id = len(self.events[event.name])
make sense

2024-07-22 15:39 UTC, pn-usaf commented on data_pipeline/in_memory_queue.py
>          InMemoryQueue object
nevermind, my bad

2024-07-22 15:44 UTC, pn-usaf commented on data_pipeline/events/in_memory_event_store.py
> +            event.id = len(self.events[event.name])
sure, you should be good here

2024-07-22 15:45 UTC, JS-USAF commented on tests/common_queue.py
>          pass
It is currently supposed to both log and move forward but I actually wouldn't need to pass after printing to keep it moving forward, would I?

2024-07-22 15:46 UTC, JS-USAF commented on tests/test_queue_with_events.py
> +def queue_with_event():
It was and I wasn't sure what to name it, good idea!

2024-07-22 15:54 UTC, pn-usaf commented on data_pipeline/in_memory_queue.py
I understand what you are saying. There isn't anything wrong with your logic, however it's "Best Practice" to not have a return in the try clause.

2024-07-22 15:58 UTC, JS-USAF commented on data_pipeline/in_memory_queue.py
> +class InMemoryQueue():
My understanding is that if the class was protected the _ would be infront of the name like _InMemoryQueue. It seems more like the _ at the end was for name uniqueness because there is a function named InMemoryQueue that I ended up changing. I will message Nick and make sure any about this and any other protected things I may have touched.

2024-07-22 16:00 UTC, JS-USAF commented on data_pipeline/queue_worker_interface.py
> +
Good idea

2024-07-22 16:11 UTC, pn-usaf commented on data_pipeline/in_memory_queue.py
>          InMemoryQueue object
nevermind, you're good here

2024-07-22 16:16 UTC, JS-USAF commented on data_pipeline/work_queue_web_api.py
> +    @staticmethod
It can be removed but by removing the unused argument it results in arguments-differ pylint errors showing up when the method is updated in the classes below. I also attempted to make the argument env_dict=None but that did not fix the unused argument error and resulted in a signature differs error later on aswell. I figured the best way to handle to error was to pylint ignore the root error

2024-07-22 16:19 UTC, pn-usaf commented on tests/common_queue.py
>          pass
you wouldn't need a pass. If pylint and ruff is complaining, we can remove it.

2024-07-22 16:20 UTC, pn-usaf commented on tests/common_queue.py
>          pass
same as above comment. If pylint and ruff is complaining, we can remove it. It's up to u to decide.

2024-07-22 16:45 UTC, pn-usaf commented on data_pipeline/in_memory_queue.py
> +class InMemoryQueue():
I've seen it both in-front and behind. I think most have the underscore in-front. I only seen the underscore trailing in one textbook. It's up to you to decide.

2024-07-23 15:47 UTC, JR-USAF commented on data_pipeline/work_queue_web_api.py
> +    @staticmethod
Is it worth fixing do you think, and adding a user suggestion?

2024-07-23 16:50 UTC, JS-USAF commented on data_pipeline/work_queue_web_api.py
> +    @staticmethod
I don't think it has an affect on anything because the QueueSettings class seems to only be used for inheritance meaning that no one should have to deal with inputting an unused argument. If QueueSetting methods were being used directly I would be more concerned. I can add a user suggestion to fix it though just incase functionality changes.

2024-07-23 16:52 UTC, JS-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +    def urlconcat(self, *components):
I reworked everywhere it is call to use the self reference and it passes argo tests now

2024-07-23 17:11 UTC, JS-USAF commented on data_pipeline/in_memory_queue.py
Ah ok I see what you mean

2024-07-23 18:50 UTC, JR-USAF approved these changes

2024-07-23 20:21 UTC, JN-USAF reviewed
I've run the pytest, pylint, and ruff checks, and they all pass.

2024-07-23 20:27 UTC, pn-usaf approved these changes

2024-07-23 20:39 UTC, JN-USAF approved these changes

2024-07-23 20:39 UTC, merged