OPAL-632 Rework QueueBase as ABC
AFMC-MAJCOM/task-queue pull request #36
Opened 2024-07-25 22:15 UTC by AM-USAF

2024-07-26 14:28 UTC, JR-USAF requested changes

2024-07-26 14:28 UTC, JR-USAF commented on data_pipeline/sql_queue.py
>  def json_sql_queue(engine:Engine, queue_name):
Remove the function json_sql_queue and put SQLModel.metadata.create_all(engine) in the initializer.

2024-07-26 14:28 UTC, JR-USAF commented on data_pipeline/s3_queue.py
>  def json_s3_queue(queue_base_s3_path):
remove json_s3_queue function and place 
```
if s5fs.HAS_S5CMD:
        print("S3 Queue is using S5CMD")
    else:
        print("S3 Queue is using S3FS")
```

In the initializer.

2024-07-26 14:28 UTC, JR-USAF commented on data_pipeline/queue_with_events.py
>  def queue_with_events(
Remove this function and put the stuff in the initializer.

2024-07-26 14:28 UTC, JR-USAF commented on data_pipeline/in_memory_queue.py
>  def in_memory_queue():
Remove this function and put the stuff needed in the initializer

2024-07-26 14:52 UTC, CK-USAF submitted a review, later dismissed
The only comments I had wouldn't get in the way of accepting this. Good job!

2024-07-26 15:46 UTC, AM-USAF commented on data_pipeline/in_memory_queue.py
>  def in_memory_queue():
I left these functions in to avoid needing to change every instance an object is made

2024-07-26 16:02 UTC, JR-USAF commented on data_pipeline/in_memory_queue.py
>  def in_memory_queue():
Ya I understand the reasoning, this is part of the reason I thought this ticket was pretty big. I think it would be nice to rework that though given those functions aren't needed anymore with the Abstract Class. I defer to Braden on this one.

2024-07-26 16:24 UTC, JS-USAF commented on data_pipeline/queue_base.py
> +        """
I think that might raise a pylint error if it does since, you could also try using a 
"raise NotImplementedError("Subclasses must implement this method.")" since it is an abstract method

2024-07-26 16:26 UTC, AM-USAF commented on data_pipeline/in_memory_queue.py
>  def in_memory_queue():
I'll ask him about it, adding all the abstract stuff didn't take as long as I thought it would so I don't mind also doing these steps

2024-07-26 16:29 UTC, JR-USAF commented on data_pipeline/in_memory_queue.py
>  def in_memory_queue():
After talking with Braden, he brings up a good point. If we remove those functions, Nicks code may need to change. So what are your thoughts on leaving the object generator function but only have it return the object, and move all other code from those functions to the init?

2024-07-26 16:34 UTC, AM-USAF commented on data_pipeline/in_memory_queue.py
>  def in_memory_queue():
I can do that

2024-07-26 19:32 UTC, JR-USAF requested changes

2024-07-26 19:32 UTC, JR-USAF commented on data_pipeline/in_memory_queue.py
>  class InMemoryQueue(QueueBase):
Why is there still a MemoryQueue dataclass, isn't InMemoryQueue supposed to replace that?

2024-07-26 19:38 UTC, AM-USAF commented on data_pipeline/in_memory_queue.py
>  class InMemoryQueue(QueueBase):
MemoryQueue is the old InMemoryQueue class, the previous way the in memory queue object was being made in in_memory_queue() was with an instance of the InMemoryQueue class - so I've replaced the old InMemoryQueue class with MemoryQueue and created the new InMemoryQueue class to create the in memory instance of the queuebase object.

So, MemoryQueue now does whatever the old InMemoryQueue class used to do, and InMemoryQueue creates the in memory queue object

2024-07-26 20:23 UTC, JR-USAF submitted a review, later dismissed

2024-07-29 13:37 UTC, CK-USAF approved these changes

2024-07-29 14:03 UTC, JR-USAF approved these changes

2024-07-29 14:05 UTC, merged