OPAL-634 Implementing get() for the api and client
AFMC-MAJCOM/task-queue pull request #51
Opened 2024-08-05 16:42 UTC by CK-USAF

2024-08-06 13:10 UTC, AM-USAF commented on tests/test_api_endpoints.py
> +    processing = queue.size(QueueItemStage.PROCESSING)
For api tests we usually also assert the status code is 200 when applicable

2024-08-06 13:16 UTC, AM-USAF commented on tests/test_work_queue_api_client.py
> +    if '1' in route:
Where does this 1 come from? I believe it's the default items in get but why is it not 888?

2024-08-06 13:38 UTC, CK-USAF commented on tests/test_api_endpoints.py
> +    processing = queue.size(QueueItemStage.PROCESSING)
added this

2024-08-06 18:38 UTC, AM-USAF commented on task_queue/work_queue_web_api.py
> +async def get(n_items:int) ->  List[Tuple[Any, Any]]:
Will queue_item_id always be a string? Could this be List[Tuple(str, Any)]

2024-08-06 18:38 UTC, AM-USAF commented on task_queue/work_queue_web_api.py
> +    Number of items to retrieve from Queue.
This should be indented

2024-08-06 18:39 UTC, AM-USAF commented on tests/test_api_endpoints.py
> +    # Moves all queue items to WAITING stage before each pytest.
We changed this, check your dms

2024-08-06 19:56 UTC, JR-USAF requested changes

2024-08-06 19:56 UTC, JR-USAF commented on task_queue/work_queue_api_client.py
> +    def put(self, items) -> None:
Why did we delete the datatype?

2024-08-06 19:56 UTC, JR-USAF commented on task_queue/in_memory_queue.py
> +    def wait(self):
I thought this was part of Anna Rays ticket. Confused why it is showing up here.

2024-08-06 19:56 UTC, JR-USAF commented on tests/test_work_queue_api_client.py
>          test_client.lookup_status('bad-url')
Maybe say 'bad-item-id' since it is an ID that is expected right?

2024-08-06 19:56 UTC, JR-USAF commented on tests/test_work_queue_api_client.py
> +    if '2' in route:
This requires you to always get 2 items when testing get right? Maybe we look for "/get" in the route?

2024-08-06 19:56 UTC, JR-USAF commented on tests/test_work_queue_api_client.py
> +    test_client.get(2)
Assign 2 to a variable and use it in .get() and in the string built for assert.

2024-08-06 19:59 UTC, JR-USAF requested changes

2024-08-06 19:59 UTC, JR-USAF commented on task_queue/work_queue_api_client.py
>          """Gets the next n Items from the Queue, moving them to PROCESSING.
We should have tests for bad input. ie. n_items (string) n_items (negative) etc. Maybe use pydantic for this

2024-08-06 22:03 UTC, JR-USAF approved these changes

2024-08-06 22:13 UTC, JR-USAF requested changes

2024-08-06 22:13 UTC, JR-USAF commented on tests/test_work_queue_api_client.py
> +    if str(get_test_value) in route:
Check if "get" is in the route. If so replace the last item in the route (split on "/") with '{item_id}' and then get rid of the `get_test_value` global variable

2024-08-07 12:13 UTC, AM-USAF commented on task_queue/work_queue_api_client.py
> +class ApiClient(QueueBase, BaseModel):
Is BaseModel getting used anywhere?

2024-08-07 13:23 UTC, CK-USAF commented on tests/test_work_queue_api_client.py
> +    if str(get_test_value) in route:
I moved get_test_value to be local to the get test and modified mock check to look for get instead

2024-08-07 14:02 UTC, JR-USAF approved these changes

2024-08-07 20:25 UTC, JR-USAF approved these changes

2024-08-07 20:32 UTC, AM-USAF commented on task_queue/work_queue_api_client.py
> +class ApiClient(QueueBase, BaseModel):
BaseModel is not needed to pass in here

2024-08-08 13:58 UTC, AM-USAF approved these changes

2024-08-08 16:02 UTC, JR-USAF approved these changes

2024-08-08 17:24 UTC, AM-USAF approved these changes

2024-08-08 19:04 UTC, merged