Opal 646
AFMC-MAJCOM/task-queue pull request #58
Opened 2024-08-08 20:47 UTC by CK-USAF

https://jira.il4.dso.mil/browse/OPAL-646

2024-08-09 16:04 UTC, JS-USAF commented on tests/test_api_endpoints.py
> +        client.post("/api/v1/queue/put", json={'good_item': bad_item})
This test might be easier to read if bad_item was just set to an object like "bad_item = object()" it will still raise a type error without the need to create an extra function. (This is not a blocking comment)

2024-08-09 16:04 UTC, JS-USAF approved these changes

2024-08-09 16:50 UTC, CK-USAF commented on tests/test_api_endpoints.py
> +        client.post("/api/v1/queue/put", json={'good_item': bad_item})
You're right this is more readable, added

2024-08-09 21:11 UTC, JR-USAF requested changes

2024-08-09 21:11 UTC, JR-USAF commented on task_queue/work_queue_web_api.py
> +        pair, where key is a the item ID and value is the queue item body.
remove a from where the is 'a'

2024-08-09 21:11 UTC, JR-USAF commented on task_queue/work_queue_web_api.py
> +    """Raises a value error if a give item is not serializable.
What is meant by a "give" item?

2024-08-13 13:09 UTC, AM-USAF commented on task_queue/work_queue_web_api.py
> +    return o
My branch got merged so this should exist in the pydantic file now and isn't needed here

2024-08-13 16:00 UTC, CK-USAF commented on task_queue/work_queue_web_api.py
> +    return o
I removed it from the endpoints file

2024-08-13 16:36 UTC, JR-USAF submitted a review, later dismissed

2024-08-13 16:55 UTC, JS-USAF submitted a review, later dismissed

2024-08-13 17:36 UTC, JS-USAF approved these changes

2024-08-13 17:44 UTC, JR-USAF approved these changes
Could have been better

2024-08-13 17:44 UTC, merged