OPAL 678
AFMC-MAJCOM/task-queue pull request #73
Opened 2024-08-23 19:22 UTC by JS-USAF

2024-08-27 13:25 UTC, AM-USAF commented on tests/test_validate_args.py
> +def test_handle_queue_implementation_choice_fail():
This needs a one sentence docstring

2024-08-27 15:57 UTC, JS-USAF commented on tests/test_validate_args.py
> +def test_handle_queue_implementation_choice_fail():
done

2024-08-27 17:23 UTC, JR-USAF requested changes

2024-08-27 17:23 UTC, JR-USAF commented on task_queue/cli/work_queue_service_cli.py
> +            raise AttributeError("Expected SqlEventStore instance, got None")
I don't know if you get None, you just get an event store that isn't SQL_JSON,

So maybe say in the error that only sql_json is the only implemented event store.

2024-08-27 17:23 UTC, JR-USAF commented on tests/test_validate_args.py
> +    with pytest.raises(AttributeError,
Add a passing test

2024-08-28 17:10 UTC, JS-USAF commented on task_queue/cli/work_queue_service_cli.py
> +            raise AttributeError("Expected SqlEventStore instance, got None")
The error message has been updated

2024-08-28 17:19 UTC, JR-USAF requested changes

2024-08-28 17:19 UTC, JR-USAF commented on tests/test_validate_args.py
> +    queue = handle_queue_implementation_choice(test_settings)
How do you know the test_queue is valid? What I'm trying to ask is, how do we know from the test that we aren't comparing an invalid queue to an invalid queue?

2024-08-28 17:24 UTC, JS-USAF commented on tests/test_validate_args.py
> +    queue = handle_queue_implementation_choice(test_settings)
The test queue will be valid because of the settings it was given, although I don't confirm it is valid, to do that I would probably just need to call a method for it but I am just assuming test_queue is right based on manually creating it with the mock settings

2024-08-28 17:28 UTC, JR-USAF approved these changes

2024-08-28 18:21 UTC, AM-USAF approved these changes

2024-08-28 18:23 UTC, merged