OPAL-592 Add Docstrings
AFMC-MAJCOM/task-queue pull request #8
Opened 2024-07-05 19:21 UTC by AM-USAF

2024-07-09 18:38 UTC, AB-USAF requested changes
Nothing passes the runners 🙄

2024-07-09 21:19 UTC, JS-USAF commented on tests/events/test_event_store.py
> +"""Pytets for event store functionality.
spelling error - "Pytets"

2024-07-09 21:20 UTC, JS-USAF commented on data_pipeline/events/event_store_interface.py
> +        time_since: datatime (default=None)
spelling error: "datatime" should be datetime

2024-07-09 21:21 UTC, JS-USAF commented on data_pipeline/events/in_memory_event_store.py
> +        Retuns a List of Events.
Spelling error: "Retuns"

2024-07-09 21:21 UTC, JS-USAF commented on data_pipeline/events/sql_event_store.py
> +            List ov Events
Spelling error: "ov"

2024-07-09 21:22 UTC, JS-USAF commented on data_pipeline/in_memory_queue.py
> +"""Wherein is conatained the class and functions for the In Memroy Queue.
Spelling error "conatained" & "Memroy"

2024-07-09 21:22 UTC, JS-USAF commented on data_pipeline/in_memory_queue.py
> +        """Regernerates the Index of the InMemoryQueue.
spelling error "Regernerates"

2024-07-09 21:23 UTC, JS-USAF commented on data_pipeline/in_memory_queue.py
> +    in_memeory_queue: InMemoryQueue_
spelling error: "in_memeory_queue"

2024-07-09 21:24 UTC, JS-USAF commented on data_pipeline/sql_queue.py
> +    Returns the numbre of items in the Queue at that current stage.
spelling error "numbre"

2024-07-09 21:26 UTC, JS-USAF commented on data_pipeline/events/in_memory_event_store.py
> +        time_since: datatime (default=None)
spelling error: "datatime" should be datetime

2024-07-09 21:26 UTC, JS-USAF commented on data_pipeline/events/sql_event_store.py
> +        time_since: datatime (default=None)
spelling error: "datatime" should be datetime

2024-07-09 21:29 UTC, JS-USAF commented on data_pipeline/in_memory_queue.py
> +
key not included in parameters

2024-07-09 21:41 UTC, JS-USAF commented on data_pipeline/work_queue_web_api.py
The functions parameter sections are inconsistent. Most functions with the "env_dict" parameter for example does not include a parameter section while a couple do. Some of the functions could use the parameter section added to them if they have any parameters. Look at "env_dict" for examples of differences.

2024-07-10 13:54 UTC, JS-USAF submitted a review, later dismissed
Looks good!

2024-07-10 18:47 UTC, JN-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        """Concatinates URL components into one URL.
Concatinates should be concatenates

2024-07-10 19:01 UTC, JN-USAF commented on data_pipeline/events/event.py
> +"""Class to create and Event.
Replace 'and' with 'an'

2024-07-10 20:33 UTC, JA-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        # Of an empty list.
This is the continuation of the previous line, should be lowercase

2024-07-10 20:34 UTC, JA-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        Status of Item.
What is the type of the returned value?

2024-07-10 20:35 UTC, JA-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +    def __init__(self,
'self' should be on next line.

2024-07-10 20:37 UTC, JA-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        # Handle this case by only taking the most recent one.
The start of these lines are continuations, no need to capitalize

2024-07-10 21:15 UTC, JN-USAF commented on data_pipeline/queue_with_events.py
> +"""Contains functions and classes concering Queue with Event.
Replace 'concering' with 'concerning'

2024-07-10 21:30 UTC, JN-USAF commented on data_pipeline/queue_with_events.py
> +    event_store: EventStoreInterface
Should this have a brief explanation? Like "Event Store to add Events to." or something else?

2024-07-10 22:18 UTC, JR-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +            Argo Workflows enpoint
endpoint is spelled wrong

2024-07-10 22:18 UTC, JR-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +            namespace for ArgoWorkflowQueueInterface.
This may be a kubernetes namespace. Maybe ask Nick.

2024-07-10 22:24 UTC, JR-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        queue_item_body: List
I don't believe this is a list

2024-07-10 22:24 UTC, JR-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        *components: string(s)
is this a list of strings?

2024-07-10 22:24 UTC, JR-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +            ID of Item.
Queue Item ID?

2024-07-10 22:24 UTC, JR-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        queue_item_body: List
I don't think queue_item_body is a list. It thought it was a dictionary.

2024-07-10 22:37 UTC, JR-USAF commented on tests/test_work_queue.py
> +    """Test that no is added to the work queue twice.
No what is added twice?

2024-07-10 22:37 UTC, JR-USAF commented on tests/test_queue.py
> +    """Tests that no duplicated are added to the queue.
No duplicates?

2024-07-10 22:37 UTC, JR-USAF commented on tests/events/test_event_store.py
> +        ?????
???

2024-07-10 22:37 UTC, JR-USAF commented on data_pipeline/work_queue_service_cli.py
> +        Work Queue to push jobs to.
The work queue isn't used to push jobs to. The work queue orchestrates sending jobs and updating the status for each job.

2024-07-10 22:37 UTC, JR-USAF commented on data_pipeline/work_queue_service_cli.py
> +        Queue to get items in PROCESSING items from.
Queue base is used to add, get, and view the status of items in the queue.

2024-07-10 22:37 UTC, JR-USAF commented on data_pipeline/work_queue_service_cli.py
> +    """
It doesn't always return a queue with events.

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        """Returns a submit URL.
"Returns the URL to the argo workflows server which new workflows can be submitted to"

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        """Returns the Argo Workflows URL
"Returns the URL to the argo workflows server that lists the workflows"

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        """Gets the status of Items in Argo Workflow.
"Converts information from the workflow labels into a QueueItemStage"

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/argo_workflows_queue_worker.py
>      def _get_response_ids_and_status(self, response_body):
"Converts the response body of the argo workflows server list endpoint into a dictionary of { item_id : queue_item_status }"

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        """Requests status from workflows.
"Gets the status of each workflow that was submitted by this worker from the argo workflows server"

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/events/event_store_interface.py
> +        """Adds Events to Event Store.
"Convenience method to add one or many events to the event store"

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/events/in_memory_event_store.py
> +    """Class for the InMemoryEventStore.
Suggest to add "Primarily used for prototyping and testing"

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/in_memory_queue.py
> +    """Queue items are objects in a python dictionary.
See suggestion for class docstring for the  `InMemoryEventStore`

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> -        # may not existin the queue item body payload
Careful about deleting this information - are you sure you're going to remember *why* the following lines are written the way they are?

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        Status of Item.
`QueueItemStage`

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/queue_base.py
> +    """Item Stage Class for Queue.
"The different stages that a queue item can be in"

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/queue_with_events.py
> -    # the flow control of this function looks really weird to satisfy the
See earlier comment about comments that describe why code is written the way it is.

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/s3_queue.py
> +    Returns list of contents in directory.
"Returns a list of the contents in the directory if the directory exists, otherwise returns an empty list instead of throwing an exception"

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/sql_queue.py
> +    """Creates the SQL Queue.
This class is more of a definition for the SQL queue table than just a means of creating it.

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/sql_queue.py
> +    Returns 0 if it was successful or else raises exception.
I think the return value of `add` isn't used anywhere and can be considered deprecated/dead.

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/work_queue_service_cli.py
> +    Returns an instance of the ArgoWorkflowsQueueWorker if the choice matches
"Selects the worker interface from the arguments. Currently only the ArgoWorkflowsQueueWorker is implemented."

2024-07-10 22:56 UTC, NM-USAF commented on data_pipeline/work_queue_service_cli.py
> +    Returns a Queue with Events based on the desired Queue Base choice.
"Constructs the queue implementation from the arguments."

2024-07-10 22:56 UTC, NM-USAF commented on tests/test_argo_workflows_worker_interface.py
> +    """Creates test worker.
"Creates a test worker that connects to an argo workflows instance that is port forwarded to this host on port 2746 (the default port)"

2024-07-10 22:56 UTC, NM-USAF commented on tests/test_argo_workflows_worker_interface.py
> +    """Test some items fail and some succeed.
"Test multiple items running concurrently, with some succeeding and some failing"

2024-07-10 22:56 UTC, NM-USAF commented on tests/test_queue.py
> +    """Fixture to create empty queues of all type.
"Fixture to create an empty queue of one given type"
This is then broadcasted across `ALL_QUEUE_TYPES` for each test by way of the `pytest.mark.parametrize` decorators, so each test is run four times, one for each queue type in the list.

2024-07-10 23:03 UTC, JR-USAF commented on data_pipeline/sql_queue.py
> +    queue_name: str
What

2024-07-11 18:39 UTC, AM-USAF commented on tests/events/test_event_store.py
> +        ?????
I couldn't figure out what this param is suppose to do, do you know?

2024-07-11 18:42 UTC, AM-USAF commented on data_pipeline/work_queue_service_cli.py
> +        Work Queue to push jobs to.
I was using the same verbiage as 'work_queue.push_next_jobs(to_start);, but looking into what happens in .push_next_jobs I understand what you're saying.

2024-07-11 20:59 UTC, JR-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +            String representation of item stage
Workflow phase. ["Succeeded", "Failed"]

2024-07-11 20:59 UTC, JR-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +            String to show the completion status, may be 'true' or 'false'
Completion status from the label. ["true", "false"]

2024-07-11 21:05 UTC, JA-USAF submitted a review, later dismissed

2024-07-11 21:37 UTC, JA-USAF approved these changes

2024-07-11 22:10 UTC, JR-USAF commented on data_pipeline/events/in_memory_event_store.py
> +            Desired time since.
Instead of `Desired time since`. "Get every event that was logged after the provided `time_since`."

2024-07-11 22:10 UTC, JR-USAF commented on data_pipeline/events/sql_event_store.py
> +    """Takes an event and creates an SQLEventStoreModel and returns it.
creates `a` SQLEventStoreModel

2024-07-11 22:10 UTC, JR-USAF commented on data_pipeline/events/sql_event_store.py
> +            Desired time since.
Instead of `Desired time since`. "Get every event that was logged after the provided `time_since`."

2024-07-11 22:10 UTC, JR-USAF commented on data_pipeline/in_memory_queue.py
> +        """Gets the stage of the QueueItemStage passed in.
Get the InMemoryQueue stage given a QueueItemStage.

2024-07-11 22:10 UTC, JR-USAF commented on data_pipeline/in_memory_queue.py
> +    new_items: Dict[str, Any]
We should figure out what format this dictionary is supposed to be. 

Is it key:value where key is the item ID and value is the dictionary to be added as QueueItemBody?

2024-07-11 22:21 UTC, JR-USAF commented on data_pipeline/in_memory_queue.py
> +    List of Queue Items grabbed.
change grabbed to 'retrieved'

2024-07-11 22:21 UTC, JR-USAF commented on data_pipeline/in_memory_queue.py
> +
ID of Queue Item

2024-07-11 22:21 UTC, JR-USAF commented on data_pipeline/queue_with_events.py
> +
Adds to the queue while logging the event to an event store.

2024-07-11 22:21 UTC, JR-USAF commented on data_pipeline/queue_with_events.py
> +
`Retrieves` items in ..., `logs` Event, then...

2024-07-11 22:21 UTC, JR-USAF commented on data_pipeline/queue_with_events.py
> +    """
Items `retrieved` from ...

2024-07-11 22:21 UTC, JR-USAF commented on data_pipeline/queue_with_events.py
> +        ID of Item
Is this the queue item ID?

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/queue_with_events.py
> +    """
What does QueueAddEventData do? I didn't really understand from the comment.

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/queue_with_events.py
> +    """
Queue Item ID

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/queue_with_events.py
> +
Moves queue item from PROCESSING to SUCCESS and logs the event.

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/queue_with_events.py
> +
Moves Queue item from PROCESSING to FAIL stage and logs the event.

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/queue_with_events.py
> +        ID of Item.
Queue item ID.

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/queue_with_events.py
> +        Event Store to track item movement.
Event store to log item movement

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/queue_with_events.py
> +    """Creates Queue with Events.
Returns a QueueBase object with added functionality to log events as queue items are retrieved, moved, etc.

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/queue_worker_interface.py
> +            Item ID
Queue item ID.

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/queue_worker_interface.py
> +            Contents of Queue Item body.
explain the queue item body as specified in my other comment.

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/queue_worker_interface.py
> +        """Requests status from workflows.
Poll status of all jobs sent by the worker interface.

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/queue_worker_interface.py
> +            Item ID
Queue Item ID

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/queue_worker_interface.py
> +            Contents of Queue Item body.
Explain the queue item body as specified in my other comment

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/queue_worker_interface.py
> +
Poll status of all jobs sent by the worker interface.

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/queue_worker_interface.py
> +            ID of Item.
Queue Item ID

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/queue_worker_interface.py
> +            ID of Item.
Queue Item ID

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/s3_queue.py
> +        Desired file system.
instantiated s3fs.S3FileSystem Object

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/s3_queue.py
> +        Items to add to file.
Probably need to figure out the format expected for this `items`. Is it a dictionary like before? What is expected.

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/s3_queue.py
> +        Item to add to file.
Let's figure out the format expected here for `item` and add it.

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/s3_queue.py
> +        Dictionary of Items to add Queue.
We need to figure out the expected format of `items`

2024-07-11 22:55 UTC, JR-USAF commented on data_pipeline/sql_queue.py
> +
We need to find out what the expected format of `items` is. Is it key:value where key is the queue id, and value is the queue_item_body we explained in the other comment?

2024-07-13 22:29 UTC, NM-USAF commented on data_pipeline/in_memory_queue.py
> +    new_items: Dict[str, Any]
Yes, this should be true for all queue implementations

2024-07-16 18:27 UTC, JR-USAF requested changes

2024-07-16 18:27 UTC, JR-USAF commented on data_pipeline/argo_workflows_queue_worker.py
> +        queue_item_body: List
Change "List" to "dict"

2024-07-16 18:27 UTC, JR-USAF commented on data_pipeline/sql_queue.py
> +        Dictionary of Items to add to Queue.
Dictionary of Items to add to Queue. The Key Value pairs in the dictionary are Key=index_key, and Value is the json expected when the job is submitted for processing.

2024-07-16 18:33 UTC, JR-USAF approved these changes
Nice Work!!

2024-07-16 19:20 UTC, JS-USAF approved these changes
Good job!

2024-07-16 19:44 UTC, merged