Opal 934 - Adding new worker interface
AFMC-MAJCOM/task-queue pull request #82
Opened 2024-09-09 17:01 UTC by AM-USAF

2024-09-10 19:07 UTC, JN-USAF approved these changes

2024-09-11 14:17 UTC, NC-USAF submitted a review, later dismissed

2024-09-11 20:23 UTC, AM-USAF commented on tests/test_process_worker_interface.py
> +    assert status == QueueItemStage.SUCCESS
I think this would concern more queue implementation rather than worker interface implementation. In theory, this test is only checking that there is no problem running an item that has already ran, not that the queue got updated correctly. I think the testing you are looking for is getting taken care of in common_queue.py test_requeue_list_input, where we requeue a failed item to run again and check that the item was taken out of the FAIL stage properly

2024-09-11 20:26 UTC, AM-USAF commented on tests/test_process_worker_interface.py
> +    assert sum(s == QueueItemStage.FAIL for s in statuses) == n_fail
I think what you are looking for concerns queue functionality rather than worker interface functionality. I copied this from how we test the argo worker but I can change it to be more specific (i.e. checking jobs are in the correct stage) if you want!

2024-09-11 20:44 UTC, JR-USAF requested changes

2024-09-11 20:44 UTC, JR-USAF commented on task_queue/cli/work_queue_service_cli.py
> +from task_queue.workers.process_queue_worker import ProcessWorkerInterface
an Interface Class is usually a class with all abstract function. Maybe rename to ProcessWorker

2024-09-11 20:44 UTC, JR-USAF commented on README.md
> +Jobs are created in Python Processes and each process will run a python script provided by the user.
I would provide example code on how to mount the volume, and where the mount is supposed to point inside the image for the python scripts to be visible to the Process Worker.

2024-09-11 20:44 UTC, JR-USAF commented on task_queue/config/config.py
> +    )
Maybe explicitly say that this is a path to a volume mounted directory containing python files used by the ProcessWorker.

2024-09-11 20:44 UTC, JR-USAF commented on task_queue/workers/process_queue_worker.py
> +            # Catch error that occured when running script
Do we not log the standard output unless there was an error?

2024-09-11 20:44 UTC, JR-USAF commented on task_queue/workers/process_queue_worker.py
> +            raise e
Is this error logged if it is thrown?

2024-09-11 20:48 UTC, AM-USAF commented on task_queue/workers/process_queue_worker.py
> +            raise e
it is now :)

2024-09-11 20:51 UTC, AM-USAF commented on task_queue/workers/process_queue_worker.py
> +            # Catch error that occured when running script
I'll add it now. My original thought was that is all went well then nothing would be getting returned to the user, but it would be a good idea to log which steps are being run, I'll add it

2024-09-11 21:24 UTC, AM-USAF commented on task_queue/cli/work_queue_service_cli.py
> +from task_queue.workers.process_queue_worker import ProcessWorkerInterface
Renamed to ProcessQueueWorker to mirror ArgoWorkflowsQueueWorker

2024-09-11 21:33 UTC, JR-USAF requested changes

2024-09-11 21:33 UTC, JR-USAF commented on tests/test_process_worker_interface.py
> +
How does this test make sure the args are making it to the python script?

2024-09-11 21:33 UTC, JR-USAF commented on tests/test_process_worker_interface.py
> +    with pytest.raises(ValidationError):
Check the output from the error, and assert it contains the stuff expected.

2024-09-11 21:33 UTC, JR-USAF commented on tests/test_process_worker_interface.py
> +    wait_for_finish(process_worker, queue_item_id)
Do you want to assert fail after this line?

2024-09-12 19:19 UTC, AM-USAF commented on README.md
> +Jobs are created in Python Processes and each process will run a python script provided by the user.
I am going to keep it more generalized because it isn't dependent on a volume mount, it is an optional way of storing the scripts.

2024-09-12 19:19 UTC, AM-USAF commented on task_queue/config/config.py
> +    )
I am going to keep it more generalized because it isn't dependent on a volume mount, it is an optional way of storing the scripts.

2024-09-12 19:23 UTC, AM-USAF commented on tests/test_process_worker_interface.py
> +
I've edited the python script it runs to fail if a specific arg is not passed in, that should address this comment now.

2024-09-12 19:26 UTC, AM-USAF commented on tests/test_process_worker_interface.py
> +    with pytest.raises(ValidationError):
done

2024-09-12 20:39 UTC, AM-USAF commented on tests/test_process_worker_interface.py
> +    wait_for_finish(process_worker, queue_item_id)
No, that is covered in test_process_worker_fail

2024-09-13 14:48 UTC, JN-USAF approved these changes

2024-09-16 19:19 UTC, AM-USAF commented on tests/test_process_worker_interface.py
> +    wait_for_finish(process_worker, queue_item_id)
I guess my point was that if the job didn't fail properly, then test_process_worker_fail would catch it and the assert wasn't needed here but I've gone ahead an added it

2024-09-16 20:13 UTC, JR-USAF approved these changes

2024-09-16 21:36 UTC, NC-USAF approved these changes

2024-09-17 13:09 UTC, merged